#file_obj1=open("//home//sony//ptrain//Files//files.txt")
file_obj1=open("files.txt")
#file_obj1=open("files.txt","w")
#file_obj1.close()
print("File name: ",file_obj1.name)
print("File state: ",file_obj1.closed)
print("File mode: ",file_obj1.mode)
